/**
 * src/backend/ignores.ts — Ignore management (analysis + application + .snyk file generation).
 */

import * as fs from 'fs';
import * as path from 'path';
import type { SnykClient } from './snykApi';
import type { ScanResult } from './cache';

// ---------------------------------------------------------------------------
// Helpers ported from snyk-commander/ignore.py
// ---------------------------------------------------------------------------

export function isNotFixable(issue: Record<string, unknown>): boolean {
  if (issue['isUpgradable'] || issue['isPatchable'] || issue['isPinnable']) return false;
  const fi = issue['fixInfo'] as Record<string, unknown> | undefined;
  if (fi?.['isUpgradable'] || fi?.['isPatchable'] || fi?.['isPinnable'] || fi?.['isFixable']) return false;
  return true;
}

export function scoreToDays(score: number | null, severity: string): number {
  const severityFallback: Record<string, number> = {
    critical: 7,
    high: 14,
    medium: 30,
    low: 60,
  };
  if (score == null) return severityFallback[severity] ?? 30;
  const s = Math.round(score);
  if (s <= 200) return 90;
  if (s <= 400) return 60;
  if (s <= 600) return 30;
  if (s <= 800) return 14;
  return 7;
}

export function getProjectFolder(projectName: string): string {
  let name = projectName;

  // Strip org prefix (before first /)
  const beforeBranchOrColon = name.split('(')[0].split(':')[0];
  if (beforeBranchOrColon.includes('/')) {
    name = name.split('/').slice(1).join('/');
  }

  let repo = name;
  let subpath = '';

  if (name.includes('(')) {
    repo = name.split('(')[0];
    const afterParen = name.includes(')') ? name.split(')').slice(1).join(')') : '';
    if (afterParen.startsWith(':')) subpath = afterParen.slice(1);
  } else if (name.includes(':')) {
    const parts = name.split(':');
    repo = parts[0];
    subpath = parts.slice(1).join(':');
    if (subpath.startsWith('env-') && subpath.includes(':')) {
      subpath = subpath.split(':').slice(1).join(':');
      if (subpath.startsWith('/')) subpath = subpath.slice(1);
    }
  }

  if (subpath) {
    const parts = subpath.rsplit ? subpath.rsplit('/', 1) : subpath.split('/');
    const lastPart = parts[parts.length - 1];
    if (parts.length >= 2 && lastPart.includes('.')) {
      subpath = parts.slice(0, -1).join('/');
    } else if (lastPart.includes('.') && !subpath.includes('/')) {
      subpath = '';
    }
  }

  repo = repo.trim();
  subpath = subpath.trim().replace(/^\/|\/$/g, '');

  if (subpath) return `${repo}/${subpath}`;
  return repo || 'unknown_project';
}

export function getProjectDisplayPath(projectName: string): string {
  let name = projectName;

  const beforeBranchOrColon = name.split('(')[0].split(':')[0];
  if (beforeBranchOrColon.includes('/')) {
    name = name.split('/').slice(1).join('/');
  }

  let repo = name;
  let subpath = '';

  if (name.includes('(')) {
    repo = name.split('(')[0];
    const afterParen = name.includes(')') ? name.split(')').slice(1).join(')') : '';
    if (afterParen.startsWith(':')) subpath = afterParen.slice(1);
  } else if (name.includes(':')) {
    const parts = name.split(':');
    repo = parts[0];
    subpath = parts.slice(1).join(':');
    if (subpath.startsWith('env-') && subpath.includes(':')) {
      subpath = subpath.split(':').slice(1).join(':');
      if (subpath.startsWith('/')) subpath = subpath.slice(1);
    }
  }

  repo = repo.trim();
  subpath = subpath.trim().replace(/^\/|\/$/g, '');

  if (subpath) return `${repo}/${subpath}`;
  return repo || 'unknown_project';
}

// ---------------------------------------------------------------------------
// .snyk YAML file writer (no external dep)
// ---------------------------------------------------------------------------

interface IgnoreEntry {
  reason: string;
  expires: string;
  created: string;
}

interface PolicyIgnore {
  [vulnId: string]: Array<{ '*': IgnoreEntry }>;
}

interface VulnMeta {
  id: string;
  title: string;
  severity: string;
  risk_score: number | null;
  cwe: string[];
  reachability: string;
  fixable: boolean;
}

function writeSnykFile(
  filePath: string,
  policy: { version: string; ignore: PolicyIgnore },
  vulnMetadata: Record<string, VulnMeta>,
): void {
  const lines: string[] = [];
  lines.push('# Snyk policy file — auto-generated by Snyk Commander');
  lines.push(`version: ${policy.version}`);
  lines.push('ignore:');

  for (const [vulnId, entries] of Object.entries(policy.ignore)) {
    const meta = vulnMetadata[vulnId];
    if (meta) {
      const cweStr = meta.cwe.length > 0 ? meta.cwe.join(', ') : 'N/A';
      const riskDisplay = meta.risk_score != null ? String(meta.risk_score) : 'N/A';
      lines.push(`  # ${meta.title}`);
      lines.push(`  # ID: ${vulnId}`);
      lines.push(`  # CWE: ${cweStr}`);
      lines.push(`  # Severity: ${meta.severity}`);
      lines.push(`  # Risk Score: ${riskDisplay}`);
      lines.push(`  # Reachability: ${meta.reachability}`);
      lines.push(`  # Fixable: ${meta.fixable ? 'Yes' : 'No'}`);
    }
    lines.push(`  ${vulnId}:`);
    for (const entry of entries) {
      for (const [pathKey, details] of Object.entries(entry)) {
        lines.push(`    - '${pathKey}':`);
        lines.push(`        reason: ${details.reason}`);
        lines.push(`        expires: ${details.expires}`);
        lines.push(`        created: ${details.created}`);
      }
    }
  }

  fs.writeFileSync(filePath, lines.join('\n') + '\n', 'utf8');
}

// ---------------------------------------------------------------------------
// Load existing .snyk policy (basic YAML parser for the ignore section)
// ---------------------------------------------------------------------------

function loadSnykPolicy(snykFilePath: string): Record<string, unknown> {
  try {
    // Use js-yaml — bundled via esbuild
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const yaml = require('js-yaml') as { load: (s: string) => unknown };
    if (!fs.existsSync(snykFilePath)) return { version: 'v1.5.0', ignore: {} };
    const raw = fs.readFileSync(snykFilePath, 'utf8');
    const parsed = yaml.load(raw) as Record<string, unknown> | null;
    const data = parsed ?? {};
    if (!data['ignore']) data['ignore'] = {};
    return data;
  } catch {
    return { version: 'v1.5.0', ignore: {} };
  }
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface IgnoreOperation {
  vuln_id: string;
  title: string;
  severity: string;
  risk_score: number | null;
  fixable: boolean;
  project_id: string;
  project_name: string;
  display_path: string;
  action: 'ignore' | 'unignore';
}

export interface IgnoreAnalysis {
  to_ignore: IgnoreOperation[];
  to_update: IgnoreOperation[];
  to_unignore: IgnoreOperation[];
}

export interface ApplyProgress {
  action: string;
  vuln_id: string;
  project_id: string;
  status: 'ok' | 'error';
  error?: string | null;
  done: number;
  total: number;
}

// ---------------------------------------------------------------------------
// analyzeIgnores — categorise operations needed
// ---------------------------------------------------------------------------

export function analyzeIgnores(
  results: ScanResult[],
  minRiskScore: number,
  snykFilePath: string,
): IgnoreAnalysis {
  const policy = loadSnykPolicy(snykFilePath);
  const existingIgnores = (policy['ignore'] as Record<string, unknown>) ?? {};

  const toIgnore: IgnoreOperation[] = [];
  const toUpdate: IgnoreOperation[] = [];
  const toUnignore: IgnoreOperation[] = [];

  for (const proj of results) {
    const projectId = proj.id;
    const projectName = proj.name ?? 'Unknown';
    const displayPath = getProjectDisplayPath(projectName);

    for (const rawIssue of proj.issues ?? []) {
      const issue = rawIssue as Record<string, unknown>;
      const issueData = (issue['issueData'] as Record<string, unknown>) ?? {};
      const vulnId = (issueData['id'] as string) || (issue['id'] as string) || '';
      if (!vulnId) continue;

      const priority = (issue['priority'] as Record<string, unknown>) ?? {};
      const rawScore = priority['score'];
      const score = rawScore != null ? parseInt(String(rawScore), 10) : null;
      const fixable = !isNotFixable(issue);
      const severity = (issueData['severity'] as string) ?? 'medium';

      let qualifies: boolean;
      if (minRiskScore > 0) {
        const scoreQualifies = score != null && !isNaN(score) && score >= minRiskScore;
        qualifies = !fixable && scoreQualifies;
      } else {
        qualifies = !fixable;
      }

      const alreadyIgnored = vulnId in existingIgnores;

      const baseEntry = {
        vuln_id: vulnId,
        title: (issueData['title'] as string) ?? vulnId,
        severity,
        risk_score: isNaN(score as number) ? null : score,
        fixable,
        project_id: projectId,
        project_name: projectName,
        display_path: displayPath,
      };

      if (qualifies) {
        if (alreadyIgnored) toUpdate.push({ ...baseEntry, action: 'ignore' });
        else toIgnore.push({ ...baseEntry, action: 'ignore' });
      } else if (alreadyIgnored && fixable) {
        toUnignore.push({ ...baseEntry, action: 'unignore' });
      }
    }
  }

  return { to_ignore: toIgnore, to_update: toUpdate, to_unignore: toUnignore };
}

// ---------------------------------------------------------------------------
// applyIgnores — apply via Snyk API with concurrency
// ---------------------------------------------------------------------------

async function applyWithRetry(
  fn: () => Promise<void>,
  maxRetries = 5,
): Promise<{ ok: boolean; error?: string }> {
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      await fn();
      return { ok: true };
    } catch (err) {
      const msg = String(err).toLowerCase();
      const isRateLimit = msg.includes('429') || msg.includes('rate limit') || msg.includes('too many requests');
      if (isRateLimit && attempt < maxRetries - 1) {
        await new Promise((r) => setTimeout(r, 10_000 * Math.pow(2, attempt)));
        continue;
      }
      return { ok: false, error: String(err) };
    }
  }
  return { ok: false, error: 'Max retries exceeded' };
}

export async function applyIgnores(
  client: SnykClient,
  orgId: string,
  operations: Array<{ action?: 'ignore' | 'unignore'; vuln_id: string; project_id: string }>,
  reason: string,
  expires: string,
  onProgress: (p: ApplyProgress) => void,
  disregardIfFixable = true,
): Promise<{ succeeded: number; failed: number }> {
  if (operations.length === 0) return { succeeded: 0, failed: 0 };

  const total = operations.length;
  let done = 0;
  let succeeded = 0;
  let failed = 0;

  // Apply with max 5 concurrent workers
  const CONCURRENCY = 5;
  let idx = 0;

  async function worker() {
    while (idx < operations.length) {
      const i = idx++;
      const op = operations[i];

      // Default to 'ignore' unless explicitly 'unignore'. This guards against
      // callers accidentally omitting the `action` field — silently treating
      // an unrecognised/missing action as an unignore would mean nothing ever
      // gets ignored, which is far more dangerous than the reverse.
      const action: 'ignore' | 'unignore' = op.action === 'unignore' ? 'unignore' : 'ignore';

      const { ok, error } = await applyWithRetry(async () => {
        if (action === 'ignore') {
          await client.ignoreIssue(orgId, op.project_id, op.vuln_id, reason, expires, disregardIfFixable);
        } else {
          await client.unignoreIssue(orgId, op.project_id, op.vuln_id);
        }
      });

      done++;
      if (ok) succeeded++;
      else failed++;

      onProgress({
        action,
        vuln_id: op.vuln_id,
        project_id: op.project_id,
        status: ok ? 'ok' : 'error',
        error: error ?? null,
        done,
        total,
      });
    }
  }

  const workers = Array.from({ length: Math.min(CONCURRENCY, operations.length) }, () => worker());
  await Promise.all(workers);

  return { succeeded, failed };
}

// ---------------------------------------------------------------------------
// generateSnykFiles — write per-project .snyk files
// ---------------------------------------------------------------------------

export function generateSnykFiles(
  results: ScanResult[],
  filterMode: string,
  minRiskScore: number,
  snykIgnoresDir: string,
): { files_written: number; total_ignores: number; files: string[] } {
  const validModes = ['all', 'fixable', 'non_fixable', 'non_fixable_above_score'];
  if (!validModes.includes(filterMode)) {
    throw new Error(`filterMode must be one of: ${validModes.join(', ')}`);
  }

  const now = new Date().toISOString().replace(/\.\d+Z$/, '.000Z');
  let filesWritten = 0;
  let totalIgnores = 0;
  const writtenPaths: string[] = [];

  for (const proj of results) {
    const issues = proj.issues ?? [];
    if (issues.length === 0) continue;

    const projectName = proj.name ?? 'unknown';
    const folderName = getProjectFolder(projectName);
    const policy: { version: string; ignore: PolicyIgnore } = { version: 'v1.5.0', ignore: {} };
    const vulnMetadata: Record<string, VulnMeta> = {};
    let projIgnoreCount = 0;

    for (const rawIssue of issues) {
      const issue = rawIssue as Record<string, unknown>;
      const issueData = (issue['issueData'] as Record<string, unknown>) ?? {};
      const vulnId = (issueData['id'] as string) || (issue['id'] as string) || '';
      if (!vulnId) continue;

      const notFixable = isNotFixable(issue);
      const priority = (issue['priority'] as Record<string, unknown>) ?? {};
      const rawScore = priority['score'];
      const score = rawScore != null ? parseInt(String(rawScore), 10) : null;
      const severity = (issueData['severity'] as string) ?? 'medium';

      let passes = false;
      if (filterMode === 'all') {
        passes = true;
      } else if (filterMode === 'fixable') {
        passes = !notFixable;
      } else if (filterMode === 'non_fixable') {
        passes = notFixable;
      } else if (filterMode === 'non_fixable_above_score') {
        if (!notFixable || score == null || isNaN(score)) passes = false;
        else passes = score >= minRiskScore;
      }

      if (!passes) continue;

      const days = scoreToDays(score != null && !isNaN(score) ? score : null, severity);
      const reason =
        score != null && !isNaN(score)
          ? `Accepted due to risk score of ${score}`
          : 'Accepted - not fixable';
      const expiresDate = new Date(Date.now() + days * 86400 * 1000)
        .toISOString()
        .replace(/\.\d+Z$/, '.000Z');

      policy.ignore[vulnId] = [{ '*': { reason, expires: expiresDate, created: now } }];
      vulnMetadata[vulnId] = {
        id: vulnId,
        title: (issueData['title'] as string) ?? vulnId,
        severity,
        risk_score: score != null && !isNaN(score) ? score : null,
        cwe: ((issueData['identifiers'] as Record<string, unknown>)?.['CWE'] as string[]) ?? [],
        reachability: 'N/A',
        fixable: !notFixable,
      };
      projIgnoreCount++;
    }

    if (projIgnoreCount > 0) {
      const folder = path.join(snykIgnoresDir, folderName);
      fs.mkdirSync(folder, { recursive: true });
      const snykFilePath = path.join(folder, '.snyk');
      writeSnykFile(snykFilePath, policy, vulnMetadata);
      filesWritten++;
      totalIgnores += projIgnoreCount;
      writtenPaths.push(snykFilePath);
    }
  }

  return { files_written: filesWritten, total_ignores: totalIgnores, files: writtenPaths };
}
