"""Report generation (display, markdown, CSV)."""

import csv
from datetime import datetime

from rich.table import Table

from .config import REPORTS_DIR, console


def risk_rating(score) -> tuple[str, str]:
    """Convert a Snyk risk score (1-1000) to (score_str, rating_str)."""
    if score is None or score == "N/A":
        return ("N/A", "N/A")
    try:
        s = int(score)
    except (ValueError, TypeError):
        return ("N/A", "N/A")
    if s <= 200:
        return (str(s), "Very Low")
    elif s <= 400:
        return (str(s), "Low")
    elif s <= 600:
        return (str(s), "Moderate")
    elif s <= 800:
        return (str(s), "High")
    else:
        return (str(s), "Critical")


def _build_rows(results: list[dict]) -> list[tuple]:
    """Build flat vulnerability rows from results."""
    rows = []
    row_num = 0
    for r in results:
        issues = r.get("issues", [])
        if not issues:
            continue
        for issue in issues:
            row_num += 1
            issue_data = issue.get("issueData", {})
            title = issue_data.get("title", "Unknown")
            severity = issue_data.get("severity", "unknown").capitalize()
            is_fixable = (
                issue.get("isUpgradable") or issue.get("isPatchable") or issue.get("isPinnable")
                or issue.get("fixInfo", {}).get("isUpgradable")
                or issue.get("fixInfo", {}).get("isPatchable")
                or issue.get("fixInfo", {}).get("isPinnable")
            )
            fix_str = "Yes" if is_fixable else "No"
            priority = issue.get("priority", {})
            raw_score = priority.get("score", issue_data.get("cvssScore", None))
            score_str, rating_str = risk_rating(raw_score)
            rows.append((row_num, r["name"], r.get("type", "unknown"),
                         severity, title, fix_str, score_str, rating_str))
    return rows


def display_results(results: list[dict]):
    """Display vulnerability table in the terminal."""
    table = Table(title="Vulnerability Summary", show_lines=True)
    table.add_column("#", style="dim", width=4)
    table.add_column("Project", min_width=30)
    table.add_column("Type", width=12)
    table.add_column("Severity", width=10)
    table.add_column("Vulnerability", min_width=25)
    table.add_column("Fix Available", justify="center", width=13)
    table.add_column("Risk Score", justify="right", width=10)
    table.add_column("Risk", width=10)

    rows = _build_rows(results)
    for row in rows:
        severity = row[3]
        sev_style = {"Critical": "bold red", "High": "red", "Medium": "yellow", "Low": "dim"}.get(severity, "")
        sev_display = f"[{sev_style}]{severity}[/{sev_style}]" if sev_style else severity
        fix_display = "[green]Yes[/green]" if row[5] == "Yes" else "[dim]No[/dim]"
        table.add_row(str(row[0]), row[1], row[2], sev_display, row[4],
                      fix_display, row[6], row[7])
    console.print(table)


def generate_report(org: dict, results: list[dict]):
    """Generate markdown and CSV reports listing each vulnerability as a row."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    base_name = f"vuln_report_{org.get('slug', org['id'])}_{timestamp}"
    md_path = REPORTS_DIR / f"{base_name}.md"
    csv_path = REPORTS_DIR / f"{base_name}.csv"

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    vuln_results = [r for r in results if r.get("total_vulns", 0) > 0]
    rows = _build_rows(vuln_results)

    # Markdown
    lines = [
        "# Vulnerability Summary Report",
        "",
        f"**Organization:** {org['name']}  ",
        f"**Date:** {now}  ",
        f"**Projects Scanned:** {len(results)}  ",
        "",
        "| # | Project | Type | Severity | Vulnerability | Fix Available | Risk Score | Risk |",
        "|---|---------|------|----------|---------------|---------------|------------|------|",
    ]
    for row in rows:
        lines.append(f"| {row[0]} | {row[1]} | {row[2]} | "
                     f"{row[3]} | {row[4]} | {row[5]} | {row[6]} | {row[7]} |")
    lines.append("")
    lines.append("*Generated by Snyk Commander*")

    md_path.write_text("\n".join(lines))
    console.print(f"\n[bold green]Report saved:[/bold green] {md_path}")

    # CSV
    csv_headers = ["#", "Project", "Type", "Severity", "Vulnerability",
                   "Fix Available", "Risk Score", "Risk"]
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(csv_headers)
        for row in rows:
            writer.writerow(row)

    console.print(f"[bold green]CSV saved:[/bold green] {csv_path}")
    return md_path
